{
    "extends": "stylelint-config-recommended",
    "rules":{
    # Color
    color-hex-case: lower,
    color-hex-length: long,
    color-named: always-where-possible,
    color-no-hex: null,
    color-no-invalid-hex: true,
    # Font Family
    font-family-name-quotes: always-where-recommended,
    # Font Weight
    font-weight-notation: named-where-possible,
    # Number
    number-leading-zero: always,
    number-max-precision: 2,
    number-no-trailing-zeros: true,
    length-zero-no-unit: true,
    # String
    string-no-newline: true,
    string-quotes: single,
    # Time
    time-no-imperceptible: true,
    #time-min-milliseconds: 100
    # Unit
    unit-case: lower,
    unit-whitelist: ["px","%","rem"],
    # Shorthand Property
    shorthand-property-no-redundant-values: true,
    # Declaration
    declaration-bang-space-after: never,
    declaration-bang-space-before: always,
    declaration-colon-newline-after: null,
    declaration-colon-space-after: always,
    declaration-colon-space-before: never,
    declaration-no-important: null,
    # Declaration Block
    declaration-block-no-duplicate-properties: true,
    declaration-block-no-ignored-properties: true,
    declaration-block-no-shorthand-property-overrides: true,
    declaration-block-properties-order: alphabetical,
    declaration-block-semicolon-newline-after: always,
    declaration-block-semicolon-newline-before: null,
    declaration-block-semicolon-space-after: null,
    declaration-block-semicolon-space-before: null,
    declaration-block-single-line-max-declarations: null,
    declaration-block-trailing-semicolon: always,
    # Block
    block-closing-brace-newline-after: always,
    block-closing-brace-newline-before: always,
    block-closing-brace-space-after: null,
    block-closing-brace-space-before: null,
    block-no-empty: true,
    block-no-single-line: true,
    block-opening-brace-newline-after: always,
    block-closing-brace-newline-before : always,
    block-opening-brace-newline-before: null,
    block-opening-brace-space-after: null,
    block-opening-brace-space-before: always,
    # Selector
    selector-attribute-brackets-space-inside: never,
    selector-class-pattern: '^[a-z\-]+$',
    selector-combinator-space-after: always,
    selector-combinator-space-before: always,
    selector-id-pattern: null,
    selector-max-specificity: null,
    selector-no-attribute: null,
    selector-no-combinator: null,
    selector-no-id: null,
    selector-no-qualifying-type: null,
    selector-no-type: null,
    selector-no-universal: true,
    selector-no-vendor-prefix: null,
    selector-pseudo-class-case: lower,
    selector-pseudo-element-case: lower,
    selector-pseudo-class-parentheses-space-inside: never,
    selector-pseudo-element-colon-notation: double,
    selector-root-no-composition: true,
    selector-type-case: lower,
    # Selector List
    selector-list-comma-newline-after: always,
    selector-list-comma-newline-before: null,
    selector-list-comma-space-after: null,
    selector-list-comma-space-before: null,
    # Rule
    rule-nested-empty-line-before: never,
    rule-non-nested-empty-line-before: null,
    # At Rule
    at-rule-empty-line-before: always,
    at-rule-name-case: lower,
    at-rule-no-vendor-prefix: true,
    at-rule-semicolon-newline-after: always,
    # Comment
    comment-empty-line-before: null,
    comment-whitespace-inside: always,
    comment-word-blacklist: null,
    # General
    indentation: 4,
    max-empty-lines: 1,
    max-line-length: 120,
    max-nesting-depth: 2,
    no-browser-hacks: true,
    no-descending-specificity: true,
    no-duplicate-selectors: true,
    no-eol-whitespace: true,
    no-indistinguishable-colors: true,
    no-invalid-double-slash-comments: true,
    no-missing-eof-newline: true,
    no-unknown-animations: true,
    stylelint-disable-reason: always-before
    }
}
